---

- include: selinux.yml
- include: users.yml
- include: base_box_cleanup.yml

- name: configure sshd config
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: ^UseDNS=
    line: UseDNS=no
    state: present
  notify: restart ssh

- include: virtualbox_base_box.yml
  when:
   ansible_virtualization_type == 'virtualbox'
