---
# tasks file for vagrant

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include: selinux.yml
- include: users.yml

- include: base_box.yml
  when:
    create_base_box is defined
