---
# tasks file for vagrant

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: install RedHat packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    packages
  when:
    ansible_os_family == 'RedHat'

- name: install Debian packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    packages
  when:
    ansible_os_family == 'Debian'

- include: vagrant_install.yml
  tags: install_vagrant
  when:
    install_vagrant is defined

- include: selinux.yml
  tags: vagrant_selinux

- include: users.yml
  tags: vagrant_users

- include: base_box.yml
  tags: base_box
  when:
    create_base_box is defined
